### ISSUE TITLE
Issues authenicating using a chromebook

### ISSUE THREAD

**Issue by final-form** [philplckthun/setup-strong-strongswan#4]
Hello!

Thank you very much for this script, it has been very helpful.
This isn't so much an issue as a heads-up: I am using a chromebook to connect to the VPN server (They are fickle with VPNs at the best of times) and after using the script I was unable to connect. 
The syslog stated that there was no secret to authenticate against when I attempted to connect.
I resolved this by copying the line with the user details from /etc/ppp/l2tp-secrets to /etc/ppp/chap-secrets.

After this, it connected me no problem. Just wanted to let you know in case this is an error or if I broke something.

Thanks again,
Elliot

**Comment by philplckthun** [comment]
@final-form I discovered that a certain configuration is missing, I will fix this asap

**Comment by philplckthun** [comment]
Fixed: b65eb2
