### ISSUE TITLE
Stuck at "Installing necessary dependencies"

### ISSUE THREAD

**Issue by DeanChan** [philplckthun/setup-strong-strongswan#5]
Hi there~ 

I am using a DigitalOcean Ubuntu 14.04x64 VPS. The process stuck at "Installing necessary dependencies". <code>top</code> shows that nothing's being done. 

Thanks.
Dean

**Comment by applepig** [comment]
Tried at Conoha's VPS servers, the installation seems to be stucking in this line
> call pacapt -S make g++ gcc libgmp-dev iptables xl2tpd libssl-dev

tried in these distros:
- CentOS 7.2 (64bit)
- Ubuntu 14.04 (64bit)
- Debian 8 (64bit)



Ubuntu 14.04

**Comment by philplckthun** [comment]
try to swap out the line that says `call pacapt -S make g++ gcc libgmp-dev iptables xl2tpd libssl-dev` with `pacapt -S make g++ gcc libgmp-dev iptables xl2tpd libssl-dev` and check the output, please

**Comment by applepig** [comment]
Just got the script working by apt-get install these dependencies, and commented this line.

The modification seems to work. I'll try to run in a clean install tomorrow.

**Comment by philplckthun** [comment]
@applepig In the case of `apt-get install` working, I don't see why `pacapt` would cause such an issue. The `call` command just executes other commands with redirecting their output to `/dev/null`. I guess this is confusing and looks like the script froze, so I'll change it, but this doesn't seem to be a bug
