### ISSUE TITLE
script failed to install

### ISSUE THREAD

**Issue by applepig** [philplckthun/setup-strong-strongswan#8]
Installed the script on Debian x64 from Conoha VPS, but failed to start.

Linux  3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u1 (2015-12-14) x86_64 GNU/Linux

Got this error message:
> sh: 0: getcwd() failed: No such file or directory
> /etc/init.d/vpn-assist: 23: /etc/init.d/vpn-assist: /usr/sbin/xl2tpd: not found
> /etc/init.d/vpn-assist: 24: /etc/init.d/vpn-assist: ipsec: not found

**Comment by applepig** [comment]
Found possbile problem, the image seems to be missing curl in the system

> ./setup.sh: line 185: curl: command not found

**Comment by philplckthun** [comment]
Well it should go without saying that you'd need to install curl and try again ;)

**Comment by hiperioncn** [comment]
**# show message after setup**

============================================================
Starting up VPN...


/etc/init.d/vpn-assist: 23: /etc/init.d/vpn-assist: /usr/sbin/xl2tpd: not found
/etc/init.d/vpn-assist: 24: /etc/init.d/vpn-assist: ipsec: not found

success or fail ?
